name: Immersive Railroading Build Pipeline

on: 
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          include:
            # Initialize java
            - branch: 1.7.10-forge
              java-version: '8'
            - branch: 1.10.2-forge
              java-version: '8'
            - branch: 1.11.2-forge
              java-version: '8'
            - branch: 1.12.2-forge
              java-version: '8'
            - branch: 1.14.4-forge
              java-version: '8'
            - branch: 1.15.2-forge
              java-version: '8'
            - branch: 1.16.5-forge
              java-version: '8'
            - branch: 1.17.1-forge
              java-version: '16'
            - branch: 1.18.2-forge
              java-version: '17'
            - branch: 1.19.4-forge
              java-version: '17'
            - branch: 1.20.1-forge
              java-version: '17'
            - branch: 1.20.4-neoforge
              java-version: '17'
            - branch: 1.21.1-neoforge
              java-version: '21'
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
    - name: keyscan
      run: mkdir -p ~/.ssh/ && ssh-keyscan -t rsa teamopenindustry.cc >> ~/.ssh/known_hosts
    - name: Install deps
      run: sudo apt install -y pngquant findutils xvfb
    - name: Setup Universal Mod Core (and helpers)
      env:
        BRANCH: ${{ matrix.branch }}
      run: java -jar UMCSetup.jar ${BRANCH} https
    - name: Gradle compile
      run: ./gradlew classes
    - name: Process images
      run: find src/main/resources/assets/immersiverailroading/ | grep png | xargs -I foo pngquant -s1 -f --ext .png foo
    - name: Run Data (optionalish)
      run: xvfb-run --auto-servernum ./gradlew runData || xvfb-run --auto-servernum ./gradlew runData || true
    - name: Gradle build
      run: ./gradlew build
    - name: Gradle publish
      env:
        MAVENCI_PASS: ${{ secrets.MAVENCI_PASS }}
      run: ./gradlew publish
    - uses: actions/upload-artifact@v4
      with:
        name: Immersive Railroading ${{matrix.branch}}
        path: build/libs/ImmersiveRailroading-${{matrix.branch}}-*
